# SPRING
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pintdb
    username: your_pg_user
    password: your_pg_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
